version: '3.9'

services:
  wordpress:
    image: wordpress:6.6.2-php8.2-apache
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-securepassword}
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - wordpress_data:/var/www/html
      - ./wp/wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - wp-network

  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PASSWORD:-securepassword}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootsecurepassword}
    volumes:
      - db_data:/var/lib/mysql
       - ./backups/backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD:-rootsecurepassword}
      UPLOAD_LIMIT: 64M
    depends_on:
      - db
    networks:
      - wp-network

volumes:
  wordpress_data:
  db_data:

networks:
  wp-network:
    driver: bridge